"""
TradeFlow AI — Price Data Schemas
Day 18: Request/response models for price bars and fetch logs.

Schemas vs Models:
  SQLAlchemy Model  → defines the DATABASE table structure
  Pydantic Schema   → defines the API request/response structure

They are separate because:
  - The DB model has internal fields (created_at, UUIDs) not shown to users
  - The API schema has computed fields (e.g. price_change) not in the DB
  - Validation rules differ (DB accepts NULL, API may require a value)
"""
from datetime import datetime
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field, field_validator, model_validator


# ---------------------------------------------------------------------------
# Enums as Literals — cleaner than Python Enum for Pydantic
# ---------------------------------------------------------------------------
Timeframe = Literal["1d", "1h", "15m"]
AssetType = Literal["equity", "crypto", "forex", "commodity", "custom"]
FetchStatus = Literal["SUCCESS", "FAILED", "PARTIAL"]


# ---------------------------------------------------------------------------
# PriceBar schemas
# ---------------------------------------------------------------------------

class PriceBarBase(BaseModel):
    """
    Shared fields between request and response schemas.
    Both inherit from this to avoid repetition.
    """
    symbol: str = Field(
        min_length=1,
        max_length=50,
        description="Ticker symbol e.g. RELIANCE.NS, BTCUSDT, EURUSD=X",
        examples=["RELIANCE.NS", "BTCUSDT", "EURUSD=X"],
    )
    timeframe: Timeframe = Field(
        description="Bar timeframe",
        examples=["1d"],
    )
    timestamp: datetime = Field(
        description="Bar open time (UTC timezone-aware)",
    )
    open: float = Field(gt=0, description="Opening price")
    high: float = Field(gt=0, description="Highest price in the bar")
    low: float = Field(gt=0, description="Lowest price in the bar")
    close: float = Field(gt=0, description="Closing price")
    volume: float = Field(ge=0, description="Trading volume")
    asset_type: AssetType = Field(description="Asset class")

    @model_validator(mode="after")
    def high_must_be_above_low(self) -> "PriceBarBase":
        """
        Catches bad data before it enters the database.
        high must always be >= low (a bar's high can't be lower than its low).
        Uses model_validator (runs after all fields validated) so both
        high and low are always available.
        """
        if self.high < self.low:
            raise ValueError(
                f"high ({self.high}) must be >= low ({self.low})"
            )
        return self

    @field_validator("symbol")
    @classmethod
    def symbol_uppercase(cls, v: str) -> str:
        """Normalise symbols to uppercase: reliance.ns → RELIANCE.NS"""
        return v.upper().strip()


class PriceBarResponse(PriceBarBase):
    """
    Full price bar response — what the API returns to clients.
    Includes the DB-generated id and created_at fields.

    model_config: from_attributes=True tells Pydantic to read
    attributes from SQLAlchemy ORM objects directly.
    Without this, Pydantic can't convert ORM objects to JSON.
    """
    id: UUID
    created_at: datetime

    model_config = {"from_attributes": True}


class PriceBarCreate(PriceBarBase):
    """
    Used when inserting via the CSV upload endpoint.
    No id or created_at — those are generated by the DB.
    """
    pass


class ChartBarResponse(BaseModel):
    """
    Lightweight bar format for the Lightweight Charts frontend library.
    Uses Unix timestamp (int) because that's what Lightweight Charts expects.

    The chart library needs:
    {"time": 1705276800, "open": 2567.5, "high": 2589.0, "low": 2551.25, "close": 2578.9}
    """
    time: int = Field(description="Unix timestamp (seconds)")
    open: float
    high: float
    low: float
    close: float
    volume: float

    @classmethod
    def from_price_bar(cls, bar: "PriceBarResponse") -> "ChartBarResponse":
        return cls(
            time=int(bar.timestamp.timestamp()),
            open=bar.open,
            high=bar.high,
            low=bar.low,
            close=bar.close,
            volume=bar.volume,
        )


# ---------------------------------------------------------------------------
# FetchLog schemas
# ---------------------------------------------------------------------------

class FetchLogResponse(BaseModel):
    """What the API returns when showing fetch log entries."""
    id: UUID
    symbol: str
    timeframe: str
    status: FetchStatus
    rows_saved: int
    error_msg: str | None
    fetched_at: datetime
    source: str

    model_config = {"from_attributes": True}


# ---------------------------------------------------------------------------
# CSV Upload schemas
# ---------------------------------------------------------------------------

class CSVUploadResponse(BaseModel):
    """Response after a successful CSV upload."""
    status: str = "success"
    symbol: str
    rows_received: int
    rows_saved: int
    message: str


class InstrumentSearchResult(BaseModel):
    """One result from the instrument search autocomplete."""
    symbol: str
    asset_type: str
